-- MySQL Script generated by MySQL Workbench
-- Mon Apr  6 17:31:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autotech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autotech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autotech` DEFAULT CHARACTER SET utf8 ;
USE `autotech` ;

-- -----------------------------------------------------
-- Table `autotech`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`servico` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`ordemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`ordemServico` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `carro_id` INT NOT NULL,
  `data` DATETIME NULL,
  `funcionario_id` INT NOT NULL,
  `cliente_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `carro_id`, `funcionario_id`, `cliente_cpf`),
  INDEX `fk_ordemServico_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  INDEX `fk_ordemServico_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_ordemServico_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `autotech`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemServico_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `autotech`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`usuario` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `telefone` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`funcionario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `autotech`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`cliente` (
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`cpf`, `usuario_id`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `autotech`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`ordemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`ordemServico` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `carro_id` INT NOT NULL,
  `data` DATETIME NULL,
  `funcionario_id` INT NOT NULL,
  `cliente_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `carro_id`, `funcionario_id`, `cliente_cpf`),
  INDEX `fk_ordemServico_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  INDEX `fk_ordemServico_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_ordemServico_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `autotech`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordemServico_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `autotech`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`fabricante` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`carroModelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`carroModelo` (
  `id` INT NOT NULL,
  `nomeModelo` VARCHAR(45) NULL,
  `fabricante_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fabricante_id`),
  INDEX `fk_carroModelo_fabricante1_idx` (`fabricante_id` ASC) VISIBLE,
  CONSTRAINT `fk_carroModelo_fabricante1`
    FOREIGN KEY (`fabricante_id`)
    REFERENCES `autotech`.`fabricante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`carro` (
  `placa` VARCHAR(8) NOT NULL,
  `ano` VARCHAR(4) NULL,
  `cor` VARCHAR(45) NULL,
  `carroModelo_id` INT NOT NULL,
  `cliente_cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`placa`, `carroModelo_id`, `cliente_cpf`),
  INDEX `fk_carro_carroModelo1_idx` (`carroModelo_id` ASC) VISIBLE,
  INDEX `fk_carro_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_carro_carroModelo1`
    FOREIGN KEY (`carroModelo_id`)
    REFERENCES `autotech`.`carroModelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `autotech`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`servico_has_ordemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`servico_has_ordemServico` (
  `servico_id` INT NOT NULL,
  `ordemServico_id` INT NOT NULL,
  `preco` FLOAT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`servico_id`, `ordemServico_id`, `id`),
  INDEX `fk_servico_has_ordemServico_ordemServico1_idx` (`ordemServico_id` ASC) VISIBLE,
  INDEX `fk_servico_has_ordemServico_servico1_idx` (`servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_servico_has_ordemServico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `autotech`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servico_has_ordemServico_ordemServico1`
    FOREIGN KEY (`ordemServico_id`)
    REFERENCES `autotech`.`ordemServico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`telefone` (
  `id` INT NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_telefone_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `autotech`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autotech`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autotech`.`Endereço` (
  `id` INT NOT NULL,
  `rua` VARCHAR(45) NULL,
  `número` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_Endereço_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `autotech`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
